# permissions for end users to edit agentwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentwebhook-editor-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - agentwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - agentwebhooks/status
  verbs:
  - get
