# permissions for end users to view agentwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentwebhook-viewer-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - agentwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - agentwebhooks/status
  verbs:
  - get
