---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openfeature.dev
  resources:
  - featureflagconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openfeature.dev
  resources:
  - featureflagconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - config.openfeature.dev
  resources:
  - featureflagconfigurations/status
  verbs:
  - get
  - patch
  - update
